GET http://localhost:5566/api/todos HTTP/1.1

###

POST http://localhost:5566/api/todos HTTP/1.1
content-type: application/json

{
  "todoDescription": "a sample todo"
}

###

GET http://localhost:5566/api/todos/WmxR5a HTTP/1.1

###

DELETE http://localhost:5566/api/todos/WmxR5a HTTP/1.1

###

PUT http://localhost:5566/api/todos/WmxR5a HTTP/1.1
content-type: application/json

{
  "id": "WmxR5a",
  "description": "updated todo",
  "isCompleted": true
}
