name: Continuous Integration
on:
  push:
    branches:
      - main
      - test_ci
jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: '14.15.4'
      - name: Install packages
        run: yarn install
      - name: Lint the code using ESLint
        run: yarn lint
      - name: Test using Jest
        run: yarn test:coverage
