name: Continuous Integration
on:
  push:
    branches:
      - main
      - test_ci
jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: "14.15.4"
      - name: Install packages
        run: yarn install
      - name: Lint the code using ESLint
        run: yarn lint
      - name: Test using Jest
        id: test_with_jest
        run: |
          test_stdout=$(yarn test:coverage --coverageReporters=text-summary)
          test_stdout="${test_stdout//'%'/'%25'}"
          test_stdout="${test_stdout//$'\n'/'%0A'}"
          test_stdout="${test_stdout//$'\r'/'%0D'}"
          echo "test_stdout"
          echo ${test_stdout}
          echo ::set-output name=test_coverage::"${test_stdout}"
      - name: Parse test coverage
        run: echo "${{ steps.test_with_jest.outputs.test_coverage }}"
      - name: Create Awesome Badge
        uses: schneegans/dynamic-badges-action@v1.0.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: ${{ secrets.GIST_ID }}
          filename: jest_coverage.json
          label: Hello
          message: Yohuan
          color: orange
