name: Continuous Integration
on:
  push:
    branches:
      - main
      - test_ci
jobs:
  lint-and-test:
    name: Lint and test
    runs-on: ubuntu-latest
    outputs:
      test_coverage_report: ${{ steps.test_with_jest.outputs.coverage_report }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: "14.15.4"
      - name: Install packages
        run: yarn install
      - name: Lint the code using ESLint
        run: yarn lint
      - name: Test using Jest
        id: test_with_jest
        run: |
          coverage_report=$(yarn test:coverage --coverageReporters=text-summary)
          coverage_report="${coverage_report//'%'/'%25'}"
          coverage_report="${coverage_report//$'\n'/'%0A'}"
          coverage_report="${coverage_report//$'\r'/'%0D'}"
          echo ::set-output name=coverage_report::"${coverage_report}"
  generate-badge:
    needs: lint-and-test
    name: Generate badges
    runs-on: ubuntu-latest
    steps:
      - name: Parse test coverage
        id: parse_test_coverage
        run: |
          coverage=$(echo "${{ needs.lint-and-test.outputs.test_coverage_report }}" | grep Statements | awk '{print $3}')
          echo ${coverage}
          echo ::set-output name=coverage::"${coverage}"
      - name: Generate test coverage badge
        uses: schneegans/dynamic-badges-action@v1.0.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: ${{ secrets.GIST_ID }}
          filename: jest_coverage.json
          label: Coverage
          message: ${{ steps.parse_test_coverage.outputs.coverage }}
          color: orange
