name: Continuous Integration
on:
  push:
    branches:
      - main
      - test_ci
jobs:
  lint-and-test:
    name: Lint and test
    runs-on: ubuntu-latest
    outputs:
      test-coverage-report: ${{ steps.test-with-jest.outputs.coverage_report }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: "14.15.4"
      - name: Install packages
        run: yarn install
      - name: Lint the code using ESLint
        run: yarn lint
      - name: Test using Jest
        id: test-with-jest
        run: |
          coverage_report=$(yarn test:coverage --coverageReporters=text-summary)
          coverage_report="${coverage_report//'%'/'%25'}"
          coverage_report="${coverage_report//$'\n'/'%0A'}"
          coverage_report="${coverage_report//$'\r'/'%0D'}"
          echo ::set-output name=coverage_report::"${coverage_report}"
  generate-badge:
    needs: lint-and-test
    name: Generate badges
    runs-on: ubuntu-latest
    steps:
      - name: Parse test coverage
        id: parse-test-coverage
        run: |
          statement_coverage=$(echo "${{ needs.lint-and-test.outputs.test-coverage-report }}" | grep Statements | awk '{print $3}')
          branch_coverage=$(echo "${{ needs.lint-and-test.outputs.test-coverage-report }}" | grep Branches | awk '{print $3}')
          function_coverage=$(echo "${{ needs.lint-and-test.outputs.test-coverage-report }}" | grep Functions | awk '{print $3}')
          line_coverage=$(echo "${{ needs.lint-and-test.outputs.test-coverage-report }}" | grep Lines | awk '{print $3}')
          echo ::set-output name=statement_coverage::"${statement_coverage}"
          echo ::set-output name=branch_coverage::"${branch_coverage}"
          echo ::set-output name=function_coverage::"${function_coverage}"
          echo ::set-output name=line_coverage::"${line_coverage}"
      - name: Generate badge for statement coverage
        uses: schneegans/dynamic-badges-action@v1.0.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: ${{ secrets.GIST_ID }}
          filename: jest_statement_coverage.json
          label: "Coverage:statements"
          message: ${{ steps.parse-test-coverage.outputs.statement_coverage }}
          color: orange
      - name: Generate badge for branch coverage
        uses: schneegans/dynamic-badges-action@v1.0.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: ${{ secrets.GIST_ID }}
          filename: jest_branch_coverage.json
          label: "Coverage:branches"
          message: ${{ steps.parse-test-coverage.outputs.branch_coverage }}
          color: orange
      - name: Generate badge for function coverage
        uses: schneegans/dynamic-badges-action@v1.0.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: ${{ secrets.GIST_ID }}
          filename: jest_function_coverage.json
          label: "Coverage:functions"
          message: ${{ steps.parse-test-coverage.outputs.function_coverage }}
          color: orange
      - name: Generate badge for line coverage
        uses: schneegans/dynamic-badges-action@v1.0.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: ${{ secrets.GIST_ID }}
          filename: jest_line_coverage.json
          label: "Coverage:lines"
          message: ${{ steps.parse-test-coverage.outputs.line_coverage }}
          color: orange
